blank_issues_enabled: true
contact_links:
  - name: MicroAPI Documentation
    url: https://github.com/XmmShp/MicroApi.Net/blob/main/README.md
    about: Check the documentation before opening an issue
